
# General Stettings
permalink: none

# Template Variables
title: 'EnergyHack Berlin'
github_url: 'https://github.com/okfde/energyhack'
fullurl: 'https://energyhack.de/'
exclude:
  - "CNAME"
  - "Gemfile*"
  - "*.sh"
  - "browserslist"
  - "README.md"
  - ".idea/"
  - ".git/"
  - ".bundle/"
  - "scripts/"
  - "_site/"
  - "vendor/"
